CREATE USER IF NOT EXISTS SA SALT '61e27cbed8611573' HASH '3eda5f4284d4586fce4d5d3b0b6593b2c4d4ba7a018be2853d44625780e72135' ADMIN;
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 8;
CREATE MEMORY TABLE PUBLIC.EMPLOYEE(
    ID BIGINT NOT NULL,
    AGE INTEGER,
    DOB DATE,
    FATHER_NAME VARCHAR(64),
    NAME VARCHAR(64),
    SEX VARCHAR(255)
);
ALTER TABLE PUBLIC.EMPLOYEE ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.EMPLOYEE;
INSERT INTO PUBLIC.EMPLOYEE(ID, AGE, DOB, FATHER_NAME, NAME, SEX) VALUES(5, 0, NULL, 'Sanjay', 'Vijay', NULL);
INSERT INTO PUBLIC.EMPLOYEE(ID, AGE, DOB, FATHER_NAME, NAME, SEX) VALUES(6, 0, NULL, 'Apoorv', 'Ram', NULL);
INSERT INTO PUBLIC.EMPLOYEE(ID, AGE, DOB, FATHER_NAME, NAME, SEX) VALUES(7, 0, NULL, 'Rahul', 'Sunil', NULL);
CREATE MEMORY TABLE PUBLIC.PRODUCT(
    ID BIGINT NOT NULL,
    MANUFACTURER_COMPANY_NAME VARCHAR(64),
    MODEL_NUMBER VARCHAR(64),
    PRICE INTEGER,
    PRODUCT_NAME VARCHAR(64),
    PRODUCT_TYPE VARCHAR(64)
);
ALTER TABLE PUBLIC.PRODUCT ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT;
INSERT INTO PUBLIC.PRODUCT(ID, MANUFACTURER_COMPANY_NAME, MODEL_NUMBER, PRICE, PRODUCT_NAME, PRODUCT_TYPE) VALUES(1, 'ABC', 'Q123', 0, 'Toothpaste', NULL);
INSERT INTO PUBLIC.PRODUCT(ID, MANUFACTURER_COMPANY_NAME, MODEL_NUMBER, PRICE, PRODUCT_NAME, PRODUCT_TYPE) VALUES(2, 'DEF', 'Z123', 0, 'Toothbrush', NULL);
INSERT INTO PUBLIC.PRODUCT(ID, MANUFACTURER_COMPANY_NAME, MODEL_NUMBER, PRICE, PRODUCT_NAME, PRODUCT_TYPE) VALUES(3, 'GHI', 'W123', 0, 'soap', NULL);
CREATE MEMORY TABLE PUBLIC.PRODUCT_EMPLOYEE(
    ID BIGINT NOT NULL,
    EMPLOYEE_ID BIGINT,
    PRODUCT_ID BIGINT
);
ALTER TABLE PUBLIC.PRODUCT_EMPLOYEE ADD CONSTRAINT PUBLIC.CONSTRAINT_7D PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_EMPLOYEE;
ALTER TABLE PUBLIC.PRODUCT_EMPLOYEE ADD CONSTRAINT PUBLIC.FK2CLV33J4WNPO6FSJX6A2KN4LA FOREIGN KEY(EMPLOYEE_ID) REFERENCES PUBLIC.EMPLOYEE(ID) NOCHECK;
ALTER TABLE PUBLIC.PRODUCT_EMPLOYEE ADD CONSTRAINT PUBLIC.FKP94ETER5T12WGMVT4DASQW4OS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCT(ID) NOCHECK;
